### ISSUE TITLE
UUID与DataStore结合

### ISSUE THREAD

**Issue by ghost** [lilith-avatar/avatar-ava#30]
**新功能的类型**
* Optimaztion 重构/优化 

**名称**
UUID与DataStore相结合的模块（名称待定）

**新功能/重构的描述**
生成UUID并且存储到DataStore中

**Comment by endaye** [comment]
用玩家UID和DataStore结合，故close issue

**Comment by endaye** [comment]
用玩家UID和DataStore结合，故close issue
