### ISSUE TITLE
[BUG] 手机上进入地图后，在客户端初始化完成之前会显示服务器相机

### ISSUE THREAD

**Issue by endaye** [lilith-avatar/avatar-ava#51]
**Describe the bug 描述BUG**
手机上进入地图后，在客户端初始化完成之前会显示服务器相机

**To Reproduce 复现步骤**
Steps to reproduce the behavior 复现步骤的操作流程:
1. 手机打开游戏，地图load完成之时
2. 在显示客户端UI之前，会有几秒的时间显示服务器相机，无UI显示（空白时长根据场景内容）

**Expected behavior 目标表现**
直接切换到客户端

**Screenshots 截屏**
[bug.mp4](https://user-images.githubusercontent.com/4829591/120606854-35108600-c482-11eb-97f0-6abe7ea91389.mp4)

**Engine Version 编辑器版本**
`v0.11`

**Platform 平台**
* Smartphone 手机

**Additional context 附加信息**
尝试修复，如果不行的话，进行遮挡

**Comment by lilith-avatar-richardzhou** [comment]
需要编辑器调整，向产品组提需求
