### ISSUE TITLE
[BUG] ModuleScript 中同时使用 InitDefault 和 EventHandler 函数会导致 EventHandler 函数失效

### ISSUE THREAD

**Issue by CheapMiao** [lilith-avatar/avatar-ava#66]
**Describe the bug 描述BUG**

客户端的 ModuleScript 中同时使用 InitDefault 和 EventHandler 函数会导致 EventHandler 函数失效
调用 NetUtil.Fire_C 和 NetUtil.Broadcast 都没办法调用客户端的 EventHandler 函数

**To Reproduce 复现步骤**
Steps to reproduce the behavior 复现步骤的操作流程:

1.在任意位置新建一脚本：
```
world.OnRenderStepped:Connect(function()
	NetUtil.Broadcast('NoticeEvent','Broadcast')
	for _,v in pairs(world.Players:GetChildren()) do
		if v:IsA('PlayerInstance') == true then
			NetUtil.Fire_C('NoticeEvent',v,'Fire_C')
		end
	end
end)
```

2.在 world.Client.Module 中新建 ModuleScript，命名为 TestCModule：
```
local TestC = ModuleUtil.New('TestC', ClientBase)

function TestC:InitDefault()
	print('TestC:InitDefault')
end

function TestC:NoticeEventHandler(s)
	print(s)
end

return TestC
```

3.确认 world.Global.Define.EventsModule 中包含以下代码：
```
-- 客户端事件列表
Events.ClientEvents = {
    --通知事件
    'NoticeEvent'
}
```

**Expected behavior 目标表现**

TestCModule 中
未注释 function TestC:InitDefault() 时不会持续输出 Broadcast Fire_C
注释掉 function TestC:InitDefault() 时可以持续输出 Broadcast Fire_C

**Screenshots 截屏**

**Engine Version 编辑器版本**

编辑器Version: 0.14.0.69438
ava框架版本：3.0.0

**Platform 平台**
- [ ] Editor 编辑器
- [ √ ] PC Launcher 电脑客户端
- [ ] Smartphone 手机

**Additional context 附加信息**

[init_bug.zip](https://github.com/lilith-avatar/avatar-ava/files/6988022/init_bug.zip)

**Comment by lilith-avatar-richardzhou** [comment]
请不要在不了解InitDefault作用的情况下重写InitDefault方法，InitDefault里有关于Event绑定的逻辑。如果需要添加自己的逻辑，请继承父类。

**Comment by CheapMiao** [comment]
噢噢好的！
